<?php

namespace Jugger\Form;

use Jugger\Validator\RequireValidator;
use Jugger\Validator\NumberValidator;
use Jugger\Form\Attribute;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-22 at 14:51:31.
 */
class AttributeTest extends \PHPUnit_Framework_TestCase {
    
    public function testConstructor() {
        $attr = new Attribute([
            "name" => "attr1"
        ]);
        $this->assertEquals($attr->name, "attr1");
        //
        $attr = new Attribute([
            "name" => "attr1",
            "hint" => "hint1",
        ]);
        $this->assertEquals($attr->name, "attr1");
        $this->assertEquals($attr->hint, "hint1");
        //
        $attr = new Attribute([
            "name" => "attr1",
            "validators" => [
                new RequireValidator(),
                new RequireValidator(),
                new NumberValidator()
            ],
            "notFound" => "not fount value",
        ]);
        $this->assertEquals($attr->name, "attr1");
        $this->assertEquals($attr->validators, [
            new RequireValidator(),
            new RequireValidator(),
            new NumberValidator()
        ]);
    }
}