<?php

namespace Jugger\Form;

use Jugger\Form\Attribute;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-22 at 14:51:31.
 */
class AttributeTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Attribute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Attribute("Тестовый атрибут");
    }

    protected function initValidators() {
        $this->object->addValidator($validator);
    }

    /**
     * @covers Jugger\Form\Attribute::validate
     * @todo   Implement testValidate().
     */
    public function testValidate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jugger\Form\Attribute::addValidator
     * @todo   Implement testAddValidator().
     */
    public function testAddValidator() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
